### PR TITLE
WIP: Docker build_defs

### PR DESCRIPTION
**Pull request by vosmith**
I've started some initial work on the docker build_defs.  This should support all available options for the [docker build command](https://docs.docker.com/engine/reference/commandline/build/) as arguments to the `docker_build` function.  Most of the arguements are optional and completely ignored if not set, with the exception of the Dockerfile and image tag.

I've played around with it on a mono repo for work purposes and it will build multiple images simultaneously without issue.  I hope to include some sort of test coverage though.

Please let me know your initial thoughts!

### CODE REVIEW

**Comment by peterebden** [comment]
Thanks for the PR!

Unfortunately Docker is difficult to express as a build rule, since its commands rely on side effects which plz can't observe. That can lead to problems like plz deciding not to rebuild a target (or retrieve it from a cache or similar) and the image then not being available in Docker.

We have a set of rules that are based around `plz run` to invoke Docker which gets around that, albeit a little awkwardly. I will try to prioritise detaching them from our repo and open-sourcing them...

**Comment by mr-solebrity** [comment]
Ah, I hadn't considered the side effects that might affect a docker build!  Not quite giving up yet, but it'll take some thought linking the docker cache and plz cache if its possible.

**Comment by vosmith** [comment]
Ah, I hadn't considered side effects that might affect a docker build.  Not giving up just yet on this, but it'll take some thought to figuring out if and how a docker cache can work with the plz build cache.

**Comment by vosmith** [comment]
I was looking into the Please cacheing framework and thinking about how it could possibly interact with docker.  From my understanding, a few things are checked to determine whether or not a rebuild is needed: the rule, the source, and the secrets.  In the case of docker, the only trouble spot I see is the source, being that a change to the base image of the Dockerfile (FROM image:tag) should also trigger a build.

I think this can be determined by reading the FROM statement in the Dockerfile, searching the image in docker images, and getting the base image id.  Also we can find the image id of desired build image, and search for the base image id in the build image's history.  If anything is missing, it would require a rebuild.

I would need to make a PR in the main please repo in order for this to work, but I wanted to get your feedback.

**Comment by vosmith** [comment]
Looks like #9 should cover this

**Pull request closed without merging**
